package transactions.compensating.enums;

public enum Handlers {
    CHECK, SENDER_LOCK, RECEIVER_LOCK, SENDER_LOCK_COMPENSATOR, RECEIVER_LOCK_COMPENSATOR, SENDER_MONEY_COMPENSATOR, RECEIVER_MONEY_COMPENSATOR, SENDER_MONEY, RECEIVER_MONEY, QUOTA, DONE;
}
