package beyondcorp.google.store;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;

import beyondcorp.google.store.enums.TrustLevel;
import beyondcorp.google.store.enums.TrustPerformance;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

@Getter
@Builder(toBuilder=true)
public class Output {
    private final String transactionID;
    private final Set<Token> tokens;

    private final TrustState trustState;
    // Internal Data after chain completes and successfully logged will be set to null
    private ChainData internalData;

    @Getter
    @Setter
    @AllArgsConstructor
    // currently using properties of data as name, geo, channel
    public class TrustState {
        private String uuid;        // detail: Unique ID for username, different from transaction ID generated by system
        private TrustLevel level;
        // detail: Trust-systems use data that don't grant direct permissions but are context (which RBAC does not, it gives roles)
        private Map<String, String> data;       // can be auth, IDP, channel (or geo)
    }

    @Getter
    @Setter
    public class ChainData {
        private String transactionID;
        private TrustPerformance performance;
        private final List<String> logs;
        private int lives;
        private final AtomicInteger passed, failed;

        public ChainData(String txnID) {
            this.transactionID = txnID;
            this.logs = new ArrayList<>();
            this.lives = 3;
            this.passed = new AtomicInteger(0);
            this.failed = new AtomicInteger(0);
        }

        public void incrementPass() {
            passed.incrementAndGet();
        }

        public void incrementFail() {
            failed.incrementAndGet();
        }
    }

    public void set() {this.internalData = null;}
}
